#!/usr/bin/env python3
"""Writes lib/l10n/labels_more.dart from label JSON files (one per language).

Usage: python3 tool/gen_labels.py tool/labels/*.json
Each file: {"lang:hi": "...", "genre:action": "...", ...}; the language code is
taken from the file name (labels_<code>.json).
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = ['// Generated by tool/gen_labels.py. Do not edit.', 'const moreLabels = <String, Map<String, String>>{']
for path in sorted(sys.argv[1:]):
    code = os.path.basename(path).split('_')[1].split('.')[0]
    data = json.load(open(path, encoding='utf-8'))
    out.append(f"  '{code}': {{")
    for k in sorted(data):
        v = data[k].replace('\\', '\\\\').replace("'", "\\'")
        out.append(f"    '{k}': '{v}',")
    out.append('  },')
out.append('};')
open(os.path.join(ROOT, 'lib/l10n/labels_more.dart'), 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print('wrote', len(sys.argv) - 1, 'languages')
