"""Every model of backend/API.md, by its snake_case name.

The class name is the CamelCase of the model name. tests/pure/test_contract.py
checks this list against API.md and against tests/examples.
"""

from app.schemas.common import Base
from app.schemas.phase1 import (
    Card,
    Error,
    Health,
    IdTokenRequest,
    Me,
    MePatch,
    OtpRequest,
    RefreshRequest,
    Session,
    SyncPull,
    SyncPush,
    SyncPushResult,
    SyncRecord,
    SyncRecordSeq,
    VerifyRequest,
)
from app.schemas.phase2 import (
    BlockList,
    BlockPost,
    Feed,
    FriendList,
    FriendRequestPost,
    FriendRequestResult,
    FriendRequests,
    FriendsWhoWatched,
    Lookup,
    Match,
    ProfileView,
    ReactionPut,
    ReportPost,
    ReportResult,
    Shelf,
)
from app.schemas.phase3 import (
    Deck,
    DeckInputs,
    DeckPut,
    DeckPutResult,
    Group,
    GroupCreate,
    GroupDetail,
    GroupFilmPut,
    GroupFilms,
    GroupList,
    GroupPatch,
    GuestPost,
    InviteCode,
    JoinPost,
    Member,
    SwipesPut,
    SwipesResult,
    Tallies,
)
from app.schemas.phase4 import (
    ClosePost,
    Night,
    NightCreate,
    NightList,
    RsvpPut,
    VotesPut,
    VotesResult,
)
from app.schemas.phase5 import (
    Message,
    MessageList,
    MessagePost,
    SendFilm,
    WrapupPost,
    WrapupResult,
)

MODELS: dict[str, type[Base]] = {
    "card": Card,
    "session": Session,
    "health": Health,
    "error": Error,
    "otp_request": OtpRequest,
    "verify_request": VerifyRequest,
    "refresh_request": RefreshRequest,
    "id_token_request": IdTokenRequest,
    "me": Me,
    "me_patch": MePatch,
    "sync_record": SyncRecord,
    "sync_record_seq": SyncRecordSeq,
    "sync_push": SyncPush,
    "sync_push_result": SyncPushResult,
    "sync_pull": SyncPull,
    "lookup": Lookup,
    "friend_request_post": FriendRequestPost,
    "friend_request_result": FriendRequestResult,
    "friend_requests": FriendRequests,
    "match": Match,
    "friend_list": FriendList,
    "profile_view": ProfileView,
    "shelf": Shelf,
    "friends_who_watched": FriendsWhoWatched,
    "feed": Feed,
    "reaction_put": ReactionPut,
    "block_post": BlockPost,
    "block_list": BlockList,
    "report_post": ReportPost,
    "report_result": ReportResult,
    "member": Member,
    "group": Group,
    "group_list": GroupList,
    "group_detail": GroupDetail,
    "group_create": GroupCreate,
    "group_patch": GroupPatch,
    "invite_code": InviteCode,
    "join_post": JoinPost,
    "guest_post": GuestPost,
    "group_films": GroupFilms,
    "group_film_put": GroupFilmPut,
    "deck": Deck,
    "deck_put": DeckPut,
    "deck_put_result": DeckPutResult,
    "deck_inputs": DeckInputs,
    "swipes_put": SwipesPut,
    "swipes_result": SwipesResult,
    "tallies": Tallies,
    "night": Night,
    "night_list": NightList,
    "night_create": NightCreate,
    "votes_put": VotesPut,
    "votes_result": VotesResult,
    "close_post": ClosePost,
    "rsvp_put": RsvpPut,
    "message": Message,
    "message_list": MessageList,
    "message_post": MessagePost,
    "wrapup_post": WrapupPost,
    "wrapup_result": WrapupResult,
    "send_film": SendFilm,
}
